# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightprice-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: flightprice
  replicas: 3
  template:
    metadata:
      name: flightprice-tmpl
      labels:
        app: flightprice
    spec:
      containers:
        - name: flightprice
          image: flightprice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000