# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightprice-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: flightprice
  replicas: 3
  template:
    metadata:
      name: flightprice-tmpl
      labels:
        app: flightprice
    spec:
      containers:
        - name: flightprice
          image: gcr.io/argo-demo-401813/flight-app:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flightprice-svc
spec:
  type: NodePort
  selector:
    app: flightprice
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000